const discounts = [
  {
    id: 9827,
    title: "discount 65",
    status: true,
    type: "percentage",
    discountTiers: [{ id: 1742534136781, quantity: "76", discount: 32 }],
    selectedProduct: "Specific Tags",
    productOptions: ["fitness_tracker", "gaming_laptop", "wireless_earbuds"],
    tagsOptions: ["Gdgsj"],
    collectionOptions: "today",
    discountStrategy: "",
    combinations: {
      productDiscounts: false,
      shippingDiscounts: false,
      orderDiscounts: false,
    },
    startDate: "21-03-2025",
    endDateStatus: false,
  },
  {
    id: 121,
    title: "discount 65",
    status: true,
    type: "percentage",
    discountTiers: [{ id: 1742534136781, quantity: "76", discount: 32 }],
    selectedProduct: "Specific Tags",
    productOptions: ["fitness_tracker", "gaming_laptop", "wireless_earbuds"],
    tagsOptions: ["Gdgsj"],
    collectionOptions: "today",
    discountStrategy: "",
    combinations: {
      productDiscounts: false,
      shippingDiscounts: false,
      orderDiscounts: false,
    },
    startDate: "21-03-2025",
    endDateStatus: false,
  },
  {
    id: 1456,
    title: "discount 65",
    status: true,
    type: "percentage",
    discountTiers: [{ id: 1742534136781, quantity: "76", discount: 32 }],
    selectedProduct: "Specific Tags",
    productOptions: ["fitness_tracker", "gaming_laptop", "wireless_earbuds"],
    tagsOptions: ["Gdgsj"],
    collectionOptions: "today",
    discountStrategy: "",
    combinations: {
      productDiscounts: false,
      shippingDiscounts: false,
      orderDiscounts: false,
    },
    startDate: "21-03-2025",
    endDateStatus: false,
  },
  {
    id: 9854,
    title: "discount 65",
    status: true,
    type: "percentage",
    discountTiers: [{ id: 1742534136781, quantity: "76", discount: 32 }],
    selectedProduct: "Specific Tags",
    productOptions: ["fitness_tracker", "gaming_laptop", "wireless_earbuds"],
    tagsOptions: ["Gdgsj"],
    collectionOptions: "today",
    discountStrategy: "",
    combinations: {
      productDiscounts: false,
      shippingDiscounts: false,
      orderDiscounts: false,
    },
    startDate: "21-03-2025",
    endDateStatus: false,
  },
  {
    id: 8976,
    title: "discount 65",
    status: true,
    type: "percentage",
    discountTiers: [{ id: 1742534136781, quantity: "76", discount: 32 }],
    selectedProduct: "Specific Tags",
    productOptions: ["fitness_tracker", "gaming_laptop", "wireless_earbuds"],
    tagsOptions: ["Gdgsj"],
    collectionOptions: "today",
    discountStrategy: "",
    combinations: {
      productDiscounts: false,
      shippingDiscounts: false,
      orderDiscounts: false,
    },
    startDate: "21-03-2025",
    endDateStatus: false,
  },
];

module.exports = discounts;
