export const collectonData = [
  { label: "Modern Furniture", value: "modern_furniture" },
  { label: "Vintage Clothing", value: "vintage_clothing" },
  { label: "Handmade Crafts", value: "handmade_crafts" },
  { label: "Tech Gadgets", value: "tech_gadgets" },
  { label: "Luxury Watches", value: "luxury_watches" },
  { label: "Home Decor", value: "home_decor" },
  { label: "Sports Equipment", value: "sports_equipment" },
  { label: "Art Paintings", value: "art_paintings" },
  { label: "Kitchen Appliances", value: "kitchen_appliances" },
  { label: "Beauty Products", value: "beauty_products" },
  { label: "Travel Gear", value: "travel_gear" },
  { label: "Pet Supplies", value: "pet_supplies" },
  { label: "Gaming Accessories", value: "gaming_accessories" },
  { label: "Office Supplies", value: "office_supplies" },
  { label: "Fitness Gear", value: "fitness_gear" },
  { label: "Music Instruments", value: "music_instruments" },
  { label: "Automotive Parts", value: "automotive_parts" },
  { label: "Baby Essentials", value: "baby_essentials" },
  { label: "Garden Tools", value: "garden_tools" },
  { label: "Outdoor Adventure", value: "outdoor_adventure" },
];